version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      sanity-studio:
        patterns:
          - sanity
          - '@sanity/*'
      react:
        patterns:
          - react
          - react-dom
          - '@types/react*'

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      nextjs:
        patterns:
          - next
          - eslint-config-next
      storybook:
        patterns:
          - storybook
          - '@storybook/*'
